// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDyxPQn5TXvE_9AsWMmF_Cm4IZ4AKMih2s',
    appId: '1:732085769219:web:4c657a1821170875402a36',
    messagingSenderId: '732085769219',
    projectId: 'pemesanan-jasa-fotografer',
    authDomain: 'pemesanan-jasa-fotografer.firebaseapp.com',
    storageBucket: 'pemesanan-jasa-fotografer.firebasestorage.app',
    measurementId: 'G-77B0RCPVKC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBTa7fylrBWqPo5XOv5XY95_Hoa2657lMw',
    appId: '1:732085769219:android:f2780210709cbdb1402a36',
    messagingSenderId: '732085769219',
    projectId: 'pemesanan-jasa-fotografer',
    storageBucket: 'pemesanan-jasa-fotografer.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDNnaKvRbgUMTc3voFoDcVTwjSROdsRWV0',
    appId: '1:732085769219:ios:a3f5597a37c19347402a36',
    messagingSenderId: '732085769219',
    projectId: 'pemesanan-jasa-fotografer',
    storageBucket: 'pemesanan-jasa-fotografer.firebasestorage.app',
    iosClientId: '732085769219-2eehcbgmsg1sf682kkrblvafu5bsb6hk.apps.googleusercontent.com',
    iosBundleId: 'com.example.sistemPemesananJasaFotografi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDNnaKvRbgUMTc3voFoDcVTwjSROdsRWV0',
    appId: '1:732085769219:ios:a3f5597a37c19347402a36',
    messagingSenderId: '732085769219',
    projectId: 'pemesanan-jasa-fotografer',
    storageBucket: 'pemesanan-jasa-fotografer.firebasestorage.app',
    iosClientId: '732085769219-2eehcbgmsg1sf682kkrblvafu5bsb6hk.apps.googleusercontent.com',
    iosBundleId: 'com.example.sistemPemesananJasaFotografi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDyxPQn5TXvE_9AsWMmF_Cm4IZ4AKMih2s',
    appId: '1:732085769219:web:797bf48fc620965c402a36',
    messagingSenderId: '732085769219',
    projectId: 'pemesanan-jasa-fotografer',
    authDomain: 'pemesanan-jasa-fotografer.firebaseapp.com',
    storageBucket: 'pemesanan-jasa-fotografer.firebasestorage.app',
    measurementId: 'G-NEMS76760H',
  );
}
